#!/usr/bin/env bash
# Path A: Vercel DNS + Cloudflare Tunnel (no Cloudflare zone for DNS).
# Prerequisites: brew install cloudflare/cloudflare/cloudflared
# 1) cloudflared tunnel login   (browser — one-time)
# 2) Run this script from anywhere:  bash deploy/cloudflared/setup-path-a.sh
#    or:  ./setup-path-a.sh  (from deploy/cloudflared/)

set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-sockethr-api}"
API_HOSTNAME="${API_HOSTNAME:-api.sockethr.com}"
LOCAL_SERVICE="${LOCAL_SERVICE:-http://127.0.0.1:3000}"
CF_DIR="${HOME}/.cloudflared"
CERT="${CF_DIR}/cert.pem"
CONFIG_OUT="${CONFIG_OUT:-${CF_DIR}/config.yml}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

die() { echo "error: $*" >&2; exit 1; }

command -v cloudflared >/dev/null 2>&1 || die "cloudflared not found. Install: brew install cloudflare/cloudflare/cloudflared"

mkdir -p "${CF_DIR}"

if [[ ! -f "${CERT}" ]]; then
  echo "No Cloudflare origin cert at ${CERT}"
  echo "Run this first in a terminal (browser will open):"
  echo "  cloudflared tunnel login"
  echo "Then re-run: $0"
  exit 1
fi

get_tunnel_id_for_name() {
  cloudflared tunnel list -o json 2>/dev/null | python3 -c "
import json, sys
name = sys.argv[1]
raw = json.load(sys.stdin)
rows = raw if isinstance(raw, list) else raw.get('tunnels') or raw.get('result') or []
if not isinstance(rows, list):
    rows = [rows]
for row in rows:
    if isinstance(row, dict) and row.get('name') == name and row.get('id'):
        print(row['id'])
        sys.exit(0)
sys.exit(1)
" "${TUNNEL_NAME}" 2>/dev/null || true
}

TUNNEL_ID="$(get_tunnel_id_for_name)"

if [[ -z "${TUNNEL_ID}" ]]; then
  echo "Creating tunnel '${TUNNEL_NAME}'..."
  OUT="$(cloudflared tunnel create "${TUNNEL_NAME}" 2>&1)" || die "tunnel create failed"
  echo "${OUT}"
  TUNNEL_ID="$(echo "${OUT}" | sed -n 's/.*with id \([a-f0-9-]\{36\}\).*/\1/p')"
  [[ -n "${TUNNEL_ID}" ]] || TUNNEL_ID="$(get_tunnel_id_for_name)"
fi

[[ -n "${TUNNEL_ID}" ]] || die "could not determine tunnel UUID"

CREDS="${CF_DIR}/${TUNNEL_ID}.json"
if [[ ! -f "${CREDS}" ]]; then
  cat >&2 <<EOF
error: tunnel '${TUNNEL_NAME}' exists in Cloudflare (id ${TUNNEL_ID}) but the credentials file is missing:
  ${CREDS}

Cloudflare only shows the tunnel secret once (in this .json). It cannot be re-downloaded for the same tunnel.

Fix — recreate the tunnel on this Mac (simplest):
  1. Stop any running cloudflared that uses this tunnel (other Mac/terminal).
  2. Delete the tunnel (add -f if Cloudflare says it is still connected):
       cloudflared tunnel delete ${TUNNEL_NAME}
  3. Re-run this script:
       bash ${SCRIPT_DIR}/setup-path-a.sh

If you already set a Vercel CNAME to ${TUNNEL_ID}.cfargotunnel.com, you must change it to the NEW uuid this script prints after step 3.

Alternative: copy ${TUNNEL_ID}.json from the computer that originally ran 'tunnel create' into:
  ${CF_DIR}/
then re-run this script.
EOF
  exit 1
fi

cat > "${CONFIG_OUT}" <<EOF
# Generated by setup-path-a.sh — Path A (Vercel DNS + tunnel)
# Docs: ${REPO_ROOT}/deploy/cloudflared/README.md

tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS}

ingress:
  - hostname: ${API_HOSTNAME}
    service: ${LOCAL_SERVICE}
  - service: http_status:404
EOF

echo "Wrote ${CONFIG_OUT}"
cloudflared tunnel --config "${CONFIG_OUT}" ingress validate

echo ""
echo "=== Vercel DNS (add this record) ==="
echo "  Type:  CNAME"
echo "  Name:  api"
echo "  Value: ${TUNNEL_ID}.cfargotunnel.com"
echo ""
echo "=== Run each session (API on 3000 + tunnel) ==="
echo "  cd ${REPO_ROOT} && npm run server"
echo "  cloudflared tunnel --config ${CONFIG_OUT} run"
echo ""
echo "=== Verify (after DNS propagates) ==="
echo "  curl -sS https://${API_HOSTNAME}/health"
echo ""
